services:
  app:
    build: .
    depends_on:
      - fulcrum
      - litecoind
    environment:
      ELECTRUM_HIDDEN_SERVICE: "notyetset.onion"
      ELECTRUM_LOCAL_SERVICE: "localhost"
      ELECTRUM_PORT: "51002"
      FULCRUM_HOST: fulcrum
      FULCRUM_PORT: "50001"
      LITECOIN_HOST: litecoind
      RPC_PORT: "19443"
      RPC_USER: umbrel
      RPC_PASSWORD: umbrel
    ports:
      - "3006:3006"
    restart: on-failure

  fulcrum:
    image: cculianu/fulcrum:v2.1.1@sha256:72d8b2f9142f83a51c6c3ba2f6931b496a08bede610b28ef2315b87aa1e3bb64
    init: true
    depends_on:
      - litecoind
    environment:
      TCP: 0.0.0.0:50001
      ADMIN: 0.0.0.0:8000
      BITCOIND: litecoind:19443
      RPCUSER: umbrel
      RPCPASSWORD: umbrel
      PEERING: "false"
      ANNOUNCE: "false"
      DATA_DIR: /data
    command: Fulcrum -D /data _ENV_
    volumes:
      - ./data/fulcrum:/data
    ports:
      - "51002:50001"
    restart: on-failure

  litecoind:
    image: litecoinproject/litecoin-core:0.21.5.5@sha256:d541077a067257620648371ab88cc1fb7eb3b738ad3fc8981d75008a73df3561
    command:
      - -regtest=1
      - -server=1
      - -rpcbind=0.0.0.0
      - -rpcallowip=0.0.0.0/0
      - -rpcuser=umbrel
      - -rpcpassword=umbrel
      - -rpcport=19443
      - -port=19444
      - -fallbackfee=0.0002
    volumes:
      - ./data/litecoin:/home/litecoin/.litecoin
    restart: on-failure
